HELP_FLAG_CANDIDATES: tuple[str, ...] = ("--help", "-h")
VERSION_FLAG_CANDIDATES: tuple[str, ...] = ("--version", "-v")
SCHEMA_VERSION = "1.0"
DEFAULT_TIMEOUT = 30
DEFAULT_MAX_DEPTH = 1
DEFAULT_CONCURRENCY = 1
DEFAULT_MODEL = "gemma3:12b"
DEFAULT_TEMPERATURE = 0.0
DEFAULT_PROVIDER = "ollama"
DEFAULT_SUBCOMMAND_HELP_FORMAT = "subcommand-help"  # Format: "subcommand-help" or "help-subcommand"
